### ISSUE TITLE
database: user point balance

### ISSUE THREAD

**Issue by dbgus** [JakSimFriend/backend#2]
user의 포인트 관리를 현재 Point tabel에서만 관리를 진행중으로 파악했는데 
그것보다는 User에 balance을 balance로 관리하고 Point 혹은 PointTransaction으로 관리 후 point사용 내역을 쌓고, api에서  querying을 하는 편이 조금 더 유지 보수가 간편할 거 같습니다.

**Comment by choiyeeun1010** [comment]
넵 반영했습니다.

**Comment by choiyeeun1010** [comment]
반영 완료.
